Jed -> not found
   Commands.package                                   -> Commands.package$Command                           Jed
   Commands.package                                   -> Commands.package$StateChange                       Jed
   Commands.package$                                  -> Commands.package$Command                           Jed
   Commands.package$                                  -> Commands.package$StateChange                       Jed
   Commands.package$Command                           -> Commands.package$StateChange                       Jed
   Commands.package$StateChangeHistory                -> Commands.package$Command                           Jed
   Commands.package$StateChangeHistory                -> Commands.package$StateChange                       Jed
   Commands.package$StateChangeHistory                -> Red.Notifier                                       Jed
   Jed.EditSession                                    -> Jed.Span                                           Jed
   Jed.EditSession                                    -> Logging.package$Logger                             Jed
   Jed.EditSession                                    -> Red.Cut                                            Jed
   Jed.EditSession                                    -> Red.DocumentInterface                              Jed
   Jed.EditSession                                    -> Red.Notifier                                       Jed
   Jed.EditSession                                    -> Red.Session                                        Jed
   Jed.EditSession$                                   -> Logging.package$Loggable                           Jed
   Jed.EditSession$                                   -> Logging.package$Logger                             Jed
   Jed.EditSessionCommands                            -> Commands.package$Command                           Jed
   Jed.EditSessionCommands                            -> Jed.EditSession                                    Jed
   Jed.EditSessionCommands                            -> Logging.package$Logger                             Jed
   Jed.EditSessionCommands$                           -> Commands.package$Command                           Jed
   Jed.EditSessionCommands$                           -> Jed.EditSession                                    Jed
   Jed.EditSessionCommands$                           -> Logging.package$Loggable                           Jed
   Jed.EditSessionCommands$                           -> Logging.package$Logger                             Jed
   Jed.EditSessionHandlers                            -> Commands.package$Command                           Jed
   Jed.EditSessionHandlers                            -> Jed.EditSession                                    Jed
   Jed.EditSessionHandlers                            -> Jed.EditSessionCommands$                           Jed
   Jed.EditSessionHandlers                            -> Logging.package$Logger                             Jed
   Jed.EditSessionHandlers                            -> Red.UserInput                                      Jed
   Jed.Jedi                                           -> Jed.EditSession                                    Jed
   Jed.Jedi                                           -> Jed.UI                                             Jed
   Jed.Jedi                                           -> Red.Document                                       Jed
   Jed.NoSelection                                    -> Jed.Span                                           Jed
   Jed.NoSelection$                                   -> Jed.Span                                           Jed
   Jed.Span$                                          -> Jed.Span                                           Jed
   Jed.TextLine                                       -> Commands.package$Command                           Jed
   Jed.TextLine                                       -> Jed.EditSession                                    Jed
   Jed.TextLine                                       -> Jed.EditSessionHandlers                            Jed
   Jed.TextLine                                       -> Logging.package$Logger                             Jed
   Jed.TextLine                                       -> Red.DocumentInterface                              Jed
   Jed.TextLine                                       -> Red.DocumentView                                   Jed
   Jed.TextLine                                       -> Red.UserInput                                      Jed
   Jed.TextLine$                                      -> Logging.package$Loggable                           Jed
   Jed.TextLine$                                      -> Logging.package$Logger                             Jed
   Jed.UI                                             -> Commands.package$Command                           Jed
   Jed.UI                                             -> Commands.package$StateChangeHistory                Jed
   Jed.UI                                             -> Jed.EditSession                                    Jed
   Jed.UI                                             -> Jed.EditSessionHandlers                            Jed
   Jed.UI                                             -> Jed.TextLine                                       Jed
   Jed.UI                                             -> Logging.package$Logger                             Jed
   Jed.UI                                             -> Red.DocumentView                                   Jed
   Jed.UI$                                            -> Logging.package$Loggable                           Jed
   Jed.UI$                                            -> Logging.package$Logger                             Jed
   Logging.package                                    -> Logging.package$LogMessage                         Jed
   Logging.package                                    -> Logging.package$Loggable                           Jed
   Logging.package                                    -> Logging.package$Logger                             Jed
   Logging.package$                                   -> Logging.package$LogMessage                         Jed
   Logging.package$                                   -> Logging.package$Loggable                           Jed
   Logging.package$                                   -> Logging.package$Logger                             Jed
   Logging.package$Default$                           -> Logging.package$Loggable                           Jed
   Logging.package$Default$                           -> Logging.package$Logger                             Jed
   Logging.package$LogMessage$                        -> Logging.package$LogMessage                         Jed
   Logging.package$Loggable                           -> Logging.package$Logger                             Jed
   Logging.package$Logger                             -> Logging.package$LogMessage                         Jed
   Logging.package$Logger                             -> Logging.package$Loggable                           Jed
   Logging.package$Logger$                            -> Logging.package$Loggable                           Jed
   Red.Character                                      -> Red.UserInput                                      Jed
   Red.Character$                                     -> Red.Character                                      Jed
   Red.CursorChanged                                  -> Red.DocumentEvent                                  Jed
   Red.CursorChanged$                                 -> Red.CursorChanged                                  Jed
   Red.Cut$                                           -> Red.Cut                                            Jed
   Red.Document                                       -> Logging.package$Logger                             Jed
   Red.Document                                       -> Red.DocumentInterface                              Jed
   Red.Document                                       -> Red.TextBuffer                                     Jed
   Red.Document                                       -> Red.TextBufferIndex                                Jed
   Red.Document$                                      -> Logging.package$Loggable                           Jed
   Red.Document$                                      -> Logging.package$Logger                             Jed
   Red.DocumentChanged                                -> Red.DocumentEvent                                  Jed
   Red.DocumentChanged$                               -> Red.DocumentEvent                                  Jed
   Red.DocumentView                                   -> Logging.package$Logger                             Jed
   Red.DocumentView                                   -> Red.DocumentEvent                                  Jed
   Red.DocumentView                                   -> Red.InputPanel                                     Jed
   Red.DocumentView                                   -> Red.Session                                        Jed
   Red.DocumentView$                                  -> Logging.package$Loggable                           Jed
   Red.DocumentView$                                  -> Logging.package$Logger                             Jed
   Red.InputEventDetail                               -> Red.InputEventDetail$Buttons$                      Jed
   Red.InputEventDetail$                              -> Red.InputEventDetail$Buttons$                      Jed
   Red.InputPanel                                     -> Logging.package$Logger                             Jed
   Red.InputPanel                                     -> Red.InputPanel$Keyboard$                           Jed
   Red.InputPanel                                     -> Red.InputPanel$Mouse$                              Jed
   Red.InputPanel                                     -> Red.Notifier                                       Jed
   Red.InputPanel                                     -> Red.UserInput                                      Jed
   Red.InputPanel$                                    -> Logging.package$Loggable                           Jed
   Red.InputPanel$                                    -> Logging.package$Logger                             Jed
   Red.InputPanel$Keyboard$                           -> Red.InputPanel                                     Jed
   Red.InputPanel$Mouse$                              -> Red.InputPanel                                     Jed
   Red.Instruction                                    -> Red.UserInput                                      Jed
   Red.Instruction$                                   -> Red.Instruction                                    Jed
   Red.MouseDragged                                   -> Red.UserInput                                      Jed
   Red.MouseDragged$                                  -> Red.MouseDragged                                   Jed
   Red.MouseEntered$                                  -> Red.UserInput                                      Jed
   Red.MouseExited$                                   -> Red.UserInput                                      Jed
   Red.MousePressed                                   -> Red.UserInput                                      Jed
   Red.MousePressed$                                  -> Red.MousePressed                                   Jed
   Red.MouseReleased                                  -> Red.UserInput                                      Jed
   Red.MouseReleased$                                 -> Red.MouseReleased                                  Jed
   Red.MouseWheel                                     -> Red.UserInput                                      Jed
   Red.MouseWheel$                                    -> Red.MouseWheel                                     Jed
   Red.SelectionChanged                               -> Red.DocumentEvent                                  Jed
   Red.SelectionChanged$                              -> Red.SelectionChanged                               Jed
   Red.Sequence                                       -> Logging.package$Logger                             Jed
   Red.Sequence$                                      -> Logging.package$Loggable                           Jed
   Red.Sequence$                                      -> Logging.package$Logger                             Jed
   Red.Session                                        -> Red.DocumentInterface                              Jed
   Red.SystemClipboard                                -> Logging.package$Logger                             Jed
   Red.SystemClipboard$                               -> Logging.package$Loggable                           Jed
   Red.SystemClipboard$                               -> Logging.package$Logger                             Jed
   Red.TextBuffer                                     -> Red.Sequence                                       Jed
   Red.TextBufferIndex                                -> Logging.package$Logger                             Jed
   Red.TextBufferIndex                                -> Red.Sequence                                       Jed
   Red.TextBufferIndex$                               -> Logging.package$Loggable                           Jed
   Red.TextBufferIndex$                               -> Logging.package$Logger                             Jed
